version: '2.1'

services:
  db:
    image: mysql
    container_name: lifenodes-db
    build: .
    restart: always
    ports:
      - 3306:3306
    environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 0
          MYSQL_DATABASE: lifenode
